### ISSUE TITLE
VCVRack crash when closing

### ISSUE THREAD

**Issue by caecos** [Ahornberg/Ahornberg-VCV-Modules#11]
On Windows 10 Pro, the latest sources compiled make VCVRack crashes when closing.

**Comment by Ahornberg** [comment]
Yes, I'm aware of that. See https://github.com/VCVRack/Rack/issues/1735

**Comment by caecos** [comment]
Sorry for borthering... many thanks...

Marc

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Ahornberg <notifications@github.com>
Envoyé : Saturday, January 9, 2021 7:47:59 PM
À : Ahornberg/Ahornberg-VCV-Modules <Ahornberg-VCV-Modules@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [Ahornberg/Ahornberg-VCV-Modules] VCVRack crash when closing (#11)


Yes, I'm aware of that. See VCVRack/Rack#1735<https://github.com/VCVRack/Rack/issues/1735>

**Comment by Ahornberg** [comment]
issue fixed

**Comment by caecos** [comment]
Mille mercis!

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Ahornberg <notifications@github.com>
Envoyé : Sunday, January 10, 2021 6:56:45 AM
À : Ahornberg/Ahornberg-VCV-Modules <Ahornberg-VCV-Modules@noreply.github.com>
Cc : caecos <caecos@hotmail.ca>; Author <author@noreply.github.com>
Objet : Re: [Ahornberg/Ahornberg-VCV-Modules] VCVRack crash when closing (#11)


issue fixed
