### ISSUE TITLE
Midi Over Audio - some VST midi arps\seq don't send a signal over HOST's outputs

### ISSUE THREAD

**Issue by vcvrackideas** [Ahornberg/Ahornberg-VCV-Modules#14]
Hi, came from this post https://community.vcvrack.com/t/how-to-send-midi-out-from-vcv-host-using-module-midi-over-audio/12047/36?u=vcvrackideas
Sequencers that I tried:
https://www.kvraudio.com/product/stochas-by-audio-vitamins/downloads
RandArp from this page - https://codefn42.wordpress.com/downloads/

**Comment by Ahornberg** [comment]
could not reproduce the issue

![rand2](https://user-images.githubusercontent.com/35393886/108748238-a618d700-753e-11eb-8180-5879c12ba14b.png)
