### ISSUE TITLE
Feature Request: better modeling of tape saturation

### ISSUE THREAD

**Issue by Chaircrusher** [Ahornberg/Ahornberg-VCV-Modules#16]
I've owned a real Echoplex, and Tape Recorder's model of saturation doesn't sound much like tape saturation.  Tape Recorder gets really noisy and develops a clattering kind of distortion.  It doesn't sound like tape oversaturation.

There is a GPL-licensed Tape simulator here that you might use as a model: https://github.com/jatinchowdhury18/AnalogTapeModel

**Comment by Ahornberg** [comment]
You're right. Because there's no saturation at all, unfortunately there are only digital aliasing artefact.

Thank you for the link. I will check it out asap.

**Comment by Ahornberg** [comment]
I decided not to add any tape saturation to Tape Recorder because there are already https://library.vcvrack.com/rackwindows/tape and https://library.vcvrack.com/ChowDSP/ChowTape in the VCV Rack library.
