### ISSUE TITLE
Tape Recorder extreme voltage

### ISSUE THREAD

**Issue by paulpiko** [Ahornberg/Ahornberg-VCV-Modules#23]
I was trying Tape Recorder for the first time, and somehow ended up with extreme voltage being shown in the port tooltip.

Rack Pro 2.3.0. Windows 10. Plugin 2.1.12

![image](https://github.com/Ahornberg/Ahornberg-VCV-Modules/assets/56526215/46064379-5c99-4f13-9598-f1d65927238f)

**Comment by Ahornberg** [comment]
Please add your VCV patch file, so that I can comprehend what's going on.

**Comment by paulpiko** [comment]
Zipped patch file

[taperecorder-20230706a.zip](https://github.com/Ahornberg/Ahornberg-VCV-Modules/files/11967397/taperecorder-20230706a.zip)

**Comment by Ahornberg** [comment]
You are using some hidden features of Tape Recorder here. In your patch, Knob 1 makes the tape louder. If you run this for a long time cranked the Knob1 all up to the right, you will get extreme voltages.

It's better to set knob 1 to BIP and turn the knob to the left side, so the recorded material is erased slowly on every cycle of the tape. This is good for making a tape echo. 

[taperecorder-20230706b.zip](https://github.com/Ahornberg/Ahornberg-VCV-Modules/files/11970372/taperecorder-20230706b.zip)

**Comment by paulpiko** [comment]
OK, thanks.
