### ISSUE TITLE
Midi Poly Expression dropping pitch bend?

### ISSUE THREAD

**Issue by pupdeg** [Ahornberg/Ahornberg-VCV-Modules#24]
Using the top X port on Midi Poly Expr with a Linnstrument, I notice that if I pitch bend and then release the note, the voltage of the X port reverts back to the initial note voltage on that channel instantly, leading to a pitch change back to the original note for the release stage of a note. MIDI Poly&MPE doesn't seem to exhibit this behavior, but maybe there's a setting I'm missing.

**Comment by pupdeg** [comment]
Sure, but I'm a little curious as to why this is the default. Was it just an oversight, or is there some use case for it?

**Comment by Ahornberg** [comment]
Yes, there's a use-case (at least for me). With the VCV Host module it is possible to drive VST synths that are not made for MPE from VCV Rack. Some VSTs apply a slew to all pitchbend data, and when pitchbend is reset on note-on (MPE standard) instead of note-off (what my module does), some VSTs would sound like this:

https://www.youtube.com/watch?v=fCoIwGLAazE

From my perspective, playability is more important than following the standard
(my module doesn't follow the MPE standard in all aspects, e.g. it doesn't support a manager/master-channel).

On my module, the pitchbend value is reset immediately after the Z-value goes to zero. Usually I drive a VCA by the Z-value, but I understand that other users of my module like to do different things like applying a release-time after note-off.

So I'm going to add an option in the context menu of my module to preserve pitchbend information until the next note-on arrives on the same channel.

**Comment by pupdeg** [comment]
Ah, that makes sense. Through testing I actually encountered that issue with MIDI Poly&MPE, it seems to apply heavy slewing even in VCV. Given how fast the response is with Midi Poly Expression, I wonder if adding a short delay to the gate trigger would fix the pitch bend issue. There's also the matter of the current FW having a 10ms delay to pitch bend changes which might also be making the problem worse, which has been fixed as of this year but hasn't been "officially" released yet. (https://www.kvraudio.com/forum/viewtopic.php?t=608331 for reference)

**Comment by pupdeg** [comment]
I thought I should mention I meant in VCV rack for the delay as a fix, obviously with a VST the slew would be external. 

I've also encountered a peculiarity of the volume (Z) handling in Midi Poly Expression, it works fine on slow small movements, but when you do funky stuff like suddenly push hard, it can get "locked" to a previous value. Scoping it in comparison to MIDI Poly&MPE seemed useful for this, I've attached a few examples.

https://imgur.com/a/rR7K3qq

**Comment by Ahornberg** [comment]
> Given how fast the response is with Midi Poly Expression, I wonder if adding a short delay to the gate trigger would fix the pitch bend issue.

In VCV there are several delay modules that can be used to add a delay to any signal you want, so feel free to experiment and find the best solution for your use-case.

In contrast to the MIDI Poly&MPE module, on my nodule the Z-output is a combination of the MIDI note-on value and the pressure value coming from the hardware controller. There are 3 little knobs that look like screws to adjust the decay for the first 20 milliseconds of the note and the release phase. I implemented all this fine tuned slews to increase playability (at least for me).

If you clearly want raw data, please use the MIDI Poly&MPE module by moDllz instead.

**Comment by pupdeg** [comment]
My issue with the Z output isn't one of implementation or decay rate, it's not matching the hardware. The yellow (molDllz) response is roughly equivalent to how hard I'm pressing, the red (midi poly expression) one is wildly off in certain situations involving large pressure shifts.

**Comment by Ahornberg** [comment]
May you share the VCV patch so I can reproduce your issue?

**Comment by Ahornberg** [comment]
Here's a video that makes the difference between the module by moDllz and my module audible: https://www.youtube.com/shorts/OVSpwPCJTFg

And to avoid noise artefacts and when the volume changes quickly, I applied a slew. I tried different slew settings, and the one my modules applies is the minimum slew to preserve a clean sound.

And here's a video from the first development stage of my module, using the moDllz module for getting the MIDI data and some slew modules and some math modules: https://www.youtube.com/watch?v=X_Yesxegz9k

Of course, I could add a "raw data mode" to my module, but in this case, my module would do the same as the already existing module by moDllz. So this doesn't make sense to me.

**Comment by pupdeg** [comment]
I'm aware of the differences, I have no problem with the intended behavior and I prefer the feedback of your module. But something in the implementation isn't working properly. The easiest way to see what I'm talking about is to push instantly at maximum pressure for a prolonged period, the pressure will get stuck around 30% or so, and then when you start to release pressure it'll climb up. This behavior isn't observable when doing pressure vibrato because you're constantly increasing and reducing pressure, so it doesn't "latch".

**Comment by Ahornberg** [comment]
When I hit my LinnStrument very hard, in some cases I can reproduce what you tell. I don't want to damage my instrument, so I'm going to create a reproducable environment for further testing purpose. Please be patient.

**Comment by Ahornberg** [comment]
both issues are soveld in version 2.3.4:
* added context menu entry "Preserve Pitch after Note-Off"
* fixed bug on z-output value
